
-- Inserting departments types

INSERT INTO DEPARTMENT_TYPE (ID, NAME, DESCRIPTION, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('DEPARTMENT_TYPE_SEQ'), 'IT', 'Information Technology Department', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO DEPARTMENT_TYPE (ID, NAME, DESCRIPTION, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('DEPARTMENT_TYPE_SEQ'), 'HR', 'Human Resources Department', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO DEPARTMENT_TYPE (ID, NAME, DESCRIPTION, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('DEPARTMENT_TYPE_SEQ'), 'Finance', 'Finance Department', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Inserting departments

INSERT INTO DEPARTMENT (ID, DEPARTMENT_TYPE, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('DEPARTMENT_SEQ'), 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); -- IT department
INSERT INTO DEPARTMENT (ID, DEPARTMENT_TYPE, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('DEPARTMENT_SEQ'), 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); -- HR department
INSERT INTO DEPARTMENT (ID, DEPARTMENT_TYPE, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('DEPARTMENT_SEQ'), 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); -- Finance department

-- Inserting employees

INSERT INTO EMPLOYEE (ID, UUID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, EMAIL, DEPARTMENT, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('EMPLOYEE_SEQ'),'123e4567-e89b-12d3-a456-426614174000', 'John', 'Doe', 'Male', '1985-05-15', 'john.doe@example.com', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, UUID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, EMAIL, DEPARTMENT, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('EMPLOYEE_SEQ'),'123e4567-e89b-12d3-a456-123456789098', 'Mariusz', 'Pudzianowski', 'Male', '1985-05-22', 'mariusz.pudzianowski@example.com', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE (ID, UUID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, EMAIL, DEPARTMENT, ROW_ADDED_DT, ROW_UPDATED_DT) VALUES (NEXTVAL('EMPLOYEE_SEQ'),'123e4567-e89b-12d3-a456-098765432123', 'Adam', 'Malysz', 'Male', '1999-05-15', 'adam.malysz@example.com', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);