
DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS DEPARTMENT_TYPE;

DROP SEQUENCE IF EXISTS EMPLOYEE_SEQ;
DROP SEQUENCE IF EXISTS TICKET_SEQ;
DROP SEQUENCE IF EXISTS DEPARTMENT_TYPE_SEQ;
DROP SEQUENCE IF EXISTS DEPARTMENT_SEQ;

CREATE SEQUENCE EMPLOYEE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TICKET_SEQ START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE DEPARTMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DEPARTMENT_TYPE_SEQ START WITH 1 INCREMENT BY 1;


CREATE TABLE DEPARTMENT_TYPE (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    ROW_ADDED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ROW_UPDATED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DEPARTMENT (
    ID BIGINT PRIMARY KEY,
    DEPARTMENT_TYPE BIGINT NOT NULL,
    ROW_ADDED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ROW_UPDATED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE EMPLOYEE (
    ID BIGINT PRIMARY KEY,
    UUID VARCHAR(255) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    GENDER VARCHAR(20),
    DATE_OF_BIRTH DATE,
    EMAIL VARCHAR(255) UNIQUE,
    DEPARTMENT BIGINT,
    ROW_ADDED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ROW_UPDATED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TICKET (
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    EMPLOYEE BIGINT,
    TICKET_STATUS VARCHAR(255) NOT NULL,
    ROW_ADDED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ROW_UPDATED_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
        FOREIGN KEY (DEPARTMENT)
            REFERENCES DEPARTMENT (ID)
            ON DELETE SET NULL;
ALTER TABLE TICKET
    ADD CONSTRAINT FK_TICKET_EMPLOYEE
        FOREIGN KEY (EMPLOYEE)
            REFERENCES EMPLOYEE (ID)
            ON DELETE SET NULL;
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT FK_DEPARTMENT_DEPARTMENT_TYPE
        FOREIGN KEY (DEPARTMENT_TYPE)
            REFERENCES DEPARTMENT_TYPE (ID)
            ON DELETE SET NULL;
